dist: xenial
language: php

services:
  - mysql

matrix:
  include:
    - php: 7.3
      env: MAGENTO_VERSION=2.3.6-p1 MYSQL=mysql:5.7
    - php: 7.4
      env: MAGENTO_VERSION=2.4.2 MYSQL=mysql:8.0

before_script:
  - sh Test/Fixtures/updateMySQL.sh
  - export PATH=$PATH:$HOME/.config/composer/vendor/bin
  - composer global require object-calisthenics/phpcs-calisthenics-rules
  - composer global require magento/magento-coding-standard

script:
  - phpcs --standard=Magento2,ObjectCalisthenics .

cache:
  directories:
  - node_modules
  - $HOME/.download_cache
  - $HOME/.composer
  - $HOME/.cache/composer
